name: key check

on:
  schedule:
    - cron: "37 12 * * *"

jobs:
  test-keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - name: test:keys
        run: pnpm test:keys
        env:
          DEVICEID: ${{ secrets.FUNCTIONAL_TEST_DEVICEID }}
          VIN: ${{ secrets.FUNCTIONAL_TEST_VIN }}
          ONSTAR_USERNAME: ${{ secrets.FUNCTIONAL_TEST_USERNAME }}
          ONSTAR_PASSWORD: ${{ secrets.FUNCTIONAL_TEST_PASSWORD }}
          ONSTAR_PIN: ${{ secrets.FUNCTIONAL_TEST_ONSTARPIN }}
