name: key check

on:
  schedule:
    - cron: "37 12 * * *"

jobs:
  test-keys:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install, and test keys
        run: |
          yarn install
          yarn test:keys
        env:
          DEVICEID: ${{ secrets.FUNCTIONAL_TEST_DEVICEID }}
          VIN: ${{ secrets.FUNCTIONAL_TEST_VIN }}
          ONSTAR_USERNAME: ${{ secrets.FUNCTIONAL_TEST_USERNAME }}
          ONSTAR_PASSWORD: ${{ secrets.FUNCTIONAL_TEST_PASSWORD }}
          ONSTAR_PIN: ${{ secrets.FUNCTIONAL_TEST_ONSTARPIN }}
