name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: yarn install, and test
        run: |
          yarn install
          yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
